#!/usr/bin/env bash

#Simple script to provide arguments to
# custom .screenrc files, and concatenate
# them with a main .screenrc with settings

function usage() {
	echo "Usage: ${0##*/} screenrc"
}

#Set up a temp file for our custom .screenrc
FILE="/tmp/scrnr.$RANDOM.rc"

#Make sure we at least have one argument
if [ $# -lt 1 ]; then
	usage
	exit 1
fi

#Our first argument is the screenrc "project" file we want
#Also the name of the screen session
scrnrp="$1"

#Make sure it exists first
if [ ! -f ".screen/$scrnrp" ]; then
	echo "Not a file: .screen/$scrnrp"
	usage
	exit 1
fi

#consume first arg now that it's valid
shift

#Copy the standard screenrc into our temp screenrc
cat $HOME/.screenrc > $FILE

#If there are any positional args (to sub in the project file)
# build a command to sub them with sed
if [ $# -ge 1 ]; then
	cmd=""
	i=0
	for param in "$@"; do
		let i+=1;
		cmd=$cmd" | sed 's/\$$i/$param/' "
	done
	cmd=$cmd" | sed 's/\$\@/$@/' "
fi

#Run the command to sub if there are any substitutions,
#and add that to our temp screenrc
bash -c "cat .screen/$scrnrp $cmd >> $FILE"

#Run screen with the rcfile (reattach an existing named session if it exists)
screen -S $scrnrp -c $FILE -dRR

#Delete the temporary screenrc once our session is done
rm $FILE
